"""create initial tables

Revision ID: 76ca4754014f
Revises: 
Create Date: 2026-02-23 10:03:34.879288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76ca4754014f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=140), nullable=True),
    sa.Column('role', sa.String(length=30), server_default='ADMIN', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PAID', 'FAILED', 'CANCELLED', name='booking_status'), server_default='DRAFT', nullable=False),
    sa.Column('ticket_category', sa.Enum('STUDENT', 'STANDARD', name='ticket_category'), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('price_per_ticket', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_attendees', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('group_lead_prefix', sa.String(length=20), nullable=True),
    sa.Column('group_lead_first_name', sa.String(length=80), nullable=False),
    sa.Column('group_lead_last_name', sa.String(length=80), nullable=False),
    sa.Column('company_name', sa.String(length=140), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('group_lead_email', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default='MOLLIE', nullable=False),
    sa.Column('mollie_payment_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mollie_payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('booking_members')
    op.drop_table('bookings')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
